VideoSharingWebApp/Models/VideoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VideoSharingWebApp.Models
{
    public class VideoModel
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Title { get; set; }
        public string Path { get; set; }
        public DateTime UploadTime { get; set; }
        public string VideoDesc { get; set; }

        public int? Views { get; set; } = 0;
        public string Thumbnail { get; set; }
    }
}

VideoSharingWebApp/Controllers/VideoModelsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VideoSharingWebApp.Models;
using VideoSharingWebApp.ViewModels;
using NReco.VideoConverter;
using System.Threading.Tasks;

namespace VideoSharingWebApp.Controllers
{
    public class VideoModelsController : Controller
    {
        public static string path;
        private ApplicationDbContext db = new ApplicationDbContext();
       
        


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Details([Bind(Include = "videoModel,commentModel,newCommentModel")] VideoCommentsViewModel CM)
            {
            if (ModelState.IsValid)
            {
                CM.newCommentModel.UserName = User.Identity.GetUserName();
                db.CommentModels.Add(CM.newCommentModel);
                db.SaveChanges();
                return Details(CM.newCommentModel.VideoId);
            }

            return View();
        }
        
        public JsonResult GetThatJavaScript(VideoModel vm)
        {
            VideoModel videoModel = db.VideoModels.Find(vm.Id);
            videoModel.Views = videoModel.Views + 1;
            db.Entry(videoModel).State = EntityState.Modified;
            db.SaveChanges();
            return Json(db.VideoModels.Where(x=>x.Id == vm.Id), JsonRequestBehavior.AllowGet);
        }
        
       

        // GET: VideoModels
        public ActionResult Index(string SearchString)
        {
            if(SearchString != null)
            {

                return View(db.VideoModels.Where(x => x.Title.Contains(SearchString)));
            }
            return View(db.VideoModels.ToList());
        }

        // GET: VideoModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VideoCommentsViewModel vm = new VideoCommentsViewModel
            {
                videoModel = db.VideoModels.Find(id)
            };
            //VideoModel videoModel = db.VideoModels.Find(id);
            foreach (var c in db.CommentModels)
            {
                if(c.VideoId == vm.videoModel.Id)
                {
                    vm.commentModel.Add(c);
                }

            }
            if(vm.commentModel == null)
            {
                vm.commentModel.Add(new CommentModel { Id=0,Comment="",VideoId=0});
            }
            

            //if (videoModel == null)
            //{
            //    return HttpNotFound();
            //}
            return View(vm);
        }

        // GET: VideoModels/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: VideoModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //public string path = "";
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,Title,Path,UploadTime,VideoDesc")] VideoModel videoModel)
        {
            if (ModelState.IsValid)
            {
                
                
                //Grab username and date for a video.
                videoModel.UserId = User.Identity.GetUserName();
                videoModel.UploadTime = DateTime.Today;

                //Get video file data
                List<string> VideoData = new List<string>();
                VideoData = VideoConverter(videoModel.Path.ToString());
                videoModel.Thumbnail = VideoData[0];
                videoModel.Path = VideoData[1];

                //Save model to database.
                db.VideoModels.Add(videoModel);
                db.SaveChanges();
                
                return RedirectToAction("Index");
            }

            return View(videoModel);
        }
        
        public static string PathToVideo()
        {
            return path;
        }
        [Authorize]
        public ActionResult AddVideo()
        {
            return View();
        }
       
        //Uploading File from view to server.
        [HttpPost]
        public ActionResult AddVideo(HttpPostedFileBase file)

        {
            path = file.FileName;
            //Check if file is mp4.
            if (path.EndsWith(".mp4"))
            {
                //where to save a file.
                path = Path.Combine(Server.MapPath("~/Videos"),
                                            Path.GetFileName(file.FileName));

                
                file.SaveAs(path);
                
                //Format path for view
                path = @"/" + Path.GetFileName(file.FileName);
                ViewBag.Message = "File uploaded successfully";
                return RedirectToAction("Create");
            }
            return View();
        }
        
        //Convert video, Create thumbnail, Pass correct paths for model back
         public List<string> VideoConverter(string output)
        {
            
            List<string> videoData = new List<string>();
            string thumbnailName = output.Substring(1) + ".jpg";
            string convertedFileName = output.Substring(1);

            //Initialize converter
            var ffconverter = new FFMpegConverter();
            ConvertSettings convertSettings = new ConvertSettings
            {
                VideoFrameSize = "320x180"
            };
            

            //Convert uploaded video to common format/size
            ffconverter.ConvertMedia((Server.MapPath("~/Videos")+output), "mp4",convertedFileName, "mp4", convertSettings);
            //Create thumbnail from converted video
            ffconverter.GetVideoThumbnail((Server.MapPath("~/") + convertedFileName), thumbnailName, 5);
            System.IO.File.Delete((Server.MapPath("~/Videos")+output));
            

            //Add correct paths to video and thumbnail for model
            videoData.Add("/" + thumbnailName);
            videoData.Add("/" + convertedFileName);

            return videoData;
        }
        // GET: VideoModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VideoModel videoModel = db.VideoModels.Find(id);
            if (videoModel == null)
            {
                return HttpNotFound();
            }
            return View(videoModel);
        }

        // POST: VideoModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,Title,Path,UploadTime,VideoDesc")] VideoModel videoModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(videoModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(videoModel);
        }

        // GET: VideoModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VideoModel videoModel = db.VideoModels.Find(id);
            if (videoModel == null)
            {
                return HttpNotFound();
            }
            return View(videoModel);
        }

        // POST: VideoModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VideoModel videoModel = db.VideoModels.Find(id);
            db.VideoModels.Remove(videoModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VideoSharingWebApp/Views/VideoModels/AddVideo.cshtml
@{
    ViewBag.Title = "AddVideo";
}

<h2>AddVideo</h2>

<h2>Upload Your Video</h2>
@using (Html.BeginForm("AddVideo",
                        "VideoModels",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" id="file" accept="video/mp4" /><br />
    <input type="submit" value="Upload Image" />
    @ViewBag.Message
}

VideoSharingWebApp/Views/VideoModels/CommentView.cshtml
@model IEnumerable<VideoSharingWebApp.ViewModels.VideoCommentsViewModel>



@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.videoModel.Title)
        </td>
    </tr>
}

VideoSharingWebApp/Views/VideoModels/Create.cshtml
@model VideoSharingWebApp.Models.VideoModel


@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>VideoModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.VideoDesc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VideoDesc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VideoDesc, "", new { @class = "text-danger" })
        </div>
    </div>
    @{
        var path = VideoSharingWebApp.Controllers.VideoModelsController.PathToVideo();

    }
    <div class="form-group">

        <div class="col-md-10">

            @Html.EditorFor(model => model.Path, new { htmlAttributes = new { @class = "form-control", @Value = path, @type = "hidden" } })
            @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VideoSharingWebApp/Views/VideoModels/Delete.cshtml
@model VideoSharingWebApp.Models.VideoModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VideoModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UploadTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UploadTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoDesc)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VideoSharingWebApp/Views/VideoModels/Details.cshtml
@model VideoSharingWebApp.ViewModels.VideoCommentsViewModel

@{
    ViewBag.Title = "Details";
}



<div>
    <video id="vidya" class="dl-horizontal" style="display:block; margin-left:auto;margin-right:auto; grid-template:auto; object-fit:fill;
  position: relative;
  overflow: hidden;
  width: 100%;
  height: 100%;
  max-height:400px;
  max-width:300px;
  transform:initial;
" controls>
        <source src="@Html.DisplayFor(model => model.videoModel.Path)" type="video/mp4">

        Your browser does not support HTML5 video.
    </video>

    <dl class="dl-horizontal" style="display:block; margin-left:auto;margin-right:auto;">

        <dt style="font-size:20px">
            Title:
        </dt>
        <dd style="font-size:20px">
            @Html.DisplayFor(model => model.videoModel.Title)
        </dd>
        <dt style="font-size:20px">
            Description:
        </dt>
        <dd style="font-size:20px">
            @Html.DisplayFor(model => model.videoModel.VideoDesc)
        </dd>
        <dt style="font-size:20px">
            Creator:
        </dt>

        <dd style="font-size:20px">
            @Html.DisplayFor(model => model.videoModel.UserId)
        </dd>

        <dt style="font-size:20px">
            Date Uploaded:
        </dt>

        <dd style="font-size:20px">
            @Html.DisplayFor(model => model.videoModel.UploadTime.Day)
            @Html.DisplayFor(model => model.videoModel.UploadTime.Month)
            @Html.DisplayFor(model => model.videoModel.UploadTime.Year)

        </dd>

    </dl>
    <p style="font-size:25px">Comments</p>
    <dl style="font-size:20px">
        
        @foreach (var m in Model.commentModel)
        {
        <dd>
            <div style=" border:2px groove; padding: 10px;">
                <p>User:  @Html.DisplayFor(Model => m.UserName)</p>
                <p>Comment: @Html.DisplayFor(model => m.Comment)</p>
            </div>
            
        </dd>
        }
    </dl>
    @using (Html.BeginForm("Details", "VideoModels", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.EditorFor(model => model.newCommentModel.Comment, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            @Html.EditorFor(model => model.newCommentModel.VideoId, new { htmlAttributes = new { @class = "form-control", @type = "hidden", @Value = Model.videoModel.Id } })
        </div>
        <div class="form-group">
            <input type="submit" value="Post Comment" class="btn btn-default" />
            </div>
    }
        </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.videoModel.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
       
      
        <script type="text/javascript">

            var h = document.getElementsByTagName('video')[0];
            h.addEventListener("ended", function () { CountView(); }, true);
           
            function CountView () {

                var id = { Id: "@Model.videoModel.Id" };
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetThatJavaScript")',
                    cache: false,
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(id)
                })
            };
            
            

            
           
           
            
        </script>
        

VideoSharingWebApp/Views/VideoModels/Edit.cshtml
@model VideoSharingWebApp.Models.VideoModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VideoModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VideoSharingWebApp/Views/VideoModels/Index.cshtml
@model IEnumerable<VideoSharingWebApp.Models.VideoModel>

@{
    ViewBag.Title = "Videos";

}
<h3>Most Popular:</h3>
@foreach (var item in Model.OrderByDescending(i => i.Views).Take(3))
{
    <div style=" display: inline-block; width: 320px;
     padding: 10px; margin: 10px; border:2px groove ">

        <b>Title: @Html.DisplayFor(modelItem => item.Title)</b>
        <p>Author: @Html.DisplayFor(modelItem => item.UserId)</p>
        <button>@Html.ActionLink("Watch", "Details", new { id = item.Id })</button>

    </div>
}

<h3>The Newest Videos:</h3>
@foreach (var item in Model.OrderByDescending(i => i.Id).Take(3))
{
    <div style=" display: inline-block; width: 320px;
     padding: 10px; margin: 10px; border:2px groove ">

        <b>Title: @Html.DisplayFor(modelItem => item.Title)</b>
        <p>Author: @Html.DisplayFor(modelItem => item.UserId)</p>
        <img src= "@(item.Thumbnail)" />
        <button>@Html.ActionLink("Watch", "Details", new { id = item.Id })</button>

    </div>
}